# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BeerApiPunk' do
 use_frameworks!
 
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'SDWebImage', '~> 4.0'

end
